### ISSUE TITLE
Add support for prettier

### ISSUE THREAD

**Issue by jezikk** [misolori/vscode-symbols#10]
It would be nice to have a prettier icon for files:

- A .prettierrc file written in JSON or YAML.
- A .prettierrc.json, .prettierrc.yml, .prettierrc.yaml, or .prettierrc.json5 file.
- A .prettierrc.js, .prettierrc.cjs, prettier.config.js, or prettier.config.cjs file that exports an object using module.exports.
- A .prettierrc.toml file.

[https://prettier.io/docs/en/configuration.html](https://prettier.io/docs/en/configuration.html)

**Comment by misolori** [comment]
<img width="316" alt="CleanShot 2022-08-15 at 21 28 32@2x" src="https://user-images.githubusercontent.com/35271042/184797927-620c0bc2-c136-4f2b-8eec-d98de3a01031.png">
