### ISSUE TITLE
Add support for vite.js

### ISSUE THREAD

**Issue by jezikk** [misolori/vscode-symbols#11]
It would be nice to support a vite.js for files:

- vite.config.js

[https://vitejs.dev/config/](https://vitejs.dev/config/)

**Comment by misolori** [comment]
<img width="320" alt="CleanShot 2022-08-15 at 21 36 27@2x" src="https://user-images.githubusercontent.com/35271042/184798807-108bd314-28fc-4483-98a8-ec86259f1198.png">

**Comment by rafaelpimpa** [comment]
It's missing ``.ts`` extension, also other possible custom files like ``vite.config.electron.ts``
![image](https://user-images.githubusercontent.com/18370605/185115178-f816035b-2fa0-447a-95ec-425d4f5b8372.png)

**Comment by misolori** [comment]
Thanks for the ping, added a more expansive list that should cover this:

<img width="237" alt="CleanShot 2022-08-17 at 07 15 21@2x" src="https://user-images.githubusercontent.com/35271042/185157094-15597fc4-dbf8-4238-9db4-eaf8959fe57b.png">
