### ISSUE TITLE
Add support for .astro

### ISSUE THREAD

**Issue by caincodes** [misolori/vscode-symbols#13]
[The default icon (with the VSC plugin) can be found here.](https://github.com/withastro/language-tools/blob/main/packages/vscode/assets/lang-icon.svg)
Thanks!

**Comment by misolori** [comment]
<img width="223" alt="CleanShot 2022-08-15 at 21 43 42@2x" src="https://user-images.githubusercontent.com/35271042/184799525-97283a7f-b476-4ca6-ac1b-9a6d2348ad46.png">
