### ISSUE TITLE
Add support for Rust files (.rs)

### ISSUE THREAD

**Issue by leodr** [misolori/vscode-symbols#15]
<img width="269" alt="Screenshot 2022-08-13 at 15 03 30" src="https://user-images.githubusercontent.com/39763575/184495410-9023bcaa-07fd-42d5-9731-4ca599476859.png">

As far as I can see Rust files currently use the default file icon.

**Comment by seahindeniz** [comment]
I'm creating an app with Tauri using Rust Lang, and I'd also love to see this ✨

**Comment by misolori** [comment]
<img width="225" alt="CleanShot 2022-08-15 at 19 27 27@2x" src="https://user-images.githubusercontent.com/35271042/184785318-218a59c2-7b82-4d9e-a65e-eaa3649a0ce3.png">
