### ISSUE TITLE
Stylus lang support (.styl)

### ISSUE THREAD

**Issue by varog-norman** [misolori/vscode-symbols#16]
Thank you for such amazing icon theme. Would you add support for stylus language `.styl` also, please?

**Comment by misolori** [comment]
<img width="202" alt="CleanShot 2022-08-16 at 14 28 36@2x" src="https://user-images.githubusercontent.com/35271042/184988477-d0bbfac9-af5e-41fa-9cc3-e5a88dcdd609.png">
