### ISSUE TITLE
Scala language support

### ISSUE THREAD

**Issue by laughedelic** [misolori/vscode-symbols#17]
Hi! I love the icons. Please, consider adding support for Scala language files: `.scala`, `.sc` (Scala scripts) and related: `.sbt` for the build definition files. Example from the Material icons theme:

![Screen Shot 2022-08-13 at 19 25 15](https://user-images.githubusercontent.com/766656/184504446-bd0c60af-6f3a-43d1-954f-e994b7effe25.png)

**Comment by misolori** [comment]
<img width="186" alt="CleanShot 2022-08-16 at 14 38 36@2x" src="https://user-images.githubusercontent.com/35271042/184989911-6530ca27-ce36-4c8f-a61f-00c02a41f119.png">
