### ISSUE TITLE
Add support for next.js

### ISSUE THREAD

**Issue by jezikk** [misolori/vscode-symbols#18]
It would be nice to have a support for [next.js config](https://nextjs.org/docs/api-reference/next.config.js/introduction) files.
- next.config.js
- next.config.mjs

**Comment by FradSer** [comment]
Also add `.next` folder support in #21 .

**Comment by misolori** [comment]
Here are the updates coming soon:

<img width="196" alt="CleanShot 2022-08-14 at 14 04 17@2x" src="https://user-images.githubusercontent.com/35271042/184554872-b3fb7778-c293-47a9-b5e6-ca83e3154a97.png">

<img width="201" alt="CleanShot 2022-08-14 at 14 05 46@2x" src="https://user-images.githubusercontent.com/35271042/184554878-0c0e0f4e-2188-44cc-9a71-5fb0b45b077a.png">
