### ISSUE TITLE
add support for postcss

### ISSUE THREAD

**Issue by jezikk** [misolori/vscode-symbols#19]
It would be nice to have an icon for [postcss](https://postcss.org).
- postcss.config.js

**Comment by FradSer** [comment]
Ask the symbol version is good?
![image](https://user-images.githubusercontent.com/1439628/184585474-1d0d876a-9834-4ccf-a9b2-2129a7097a4c.png)

The original PostCSS logo below:

![image](https://user-images.githubusercontent.com/1439628/184585120-8f2c499b-62c1-4d7e-915b-2a0832bea04b.png)

**Comment by jezikk** [comment]
In my opinion it is oka. 👍🏻

**Comment by misolori** [comment]
I ended up simplifying this one a bit more:

<img width="243" alt="CleanShot 2022-08-16 at 14 50 02@2x" src="https://user-images.githubusercontent.com/35271042/184991523-958eea2c-1c4f-429d-83ed-f93cb7d046ff.png">
