### ISSUE TITLE
Add support for `.gradle` files

### ISSUE THREAD

**Issue by ameer-taghavi** [misolori/vscode-symbols#23]
as titled 🙏🏻
<img width="134" alt="image" src="https://user-images.githubusercontent.com/12966060/184613614-7591d430-d6b7-4505-8d2d-35e2b5bb2434.png">

**Comment by misolori** [comment]
<img width="236" alt="CleanShot 2022-08-16 at 14 53 19@2x" src="https://user-images.githubusercontent.com/35271042/184991922-81aa99de-2b08-4ad5-9dd5-ae7bc8227742.png">
