### ISSUE TITLE
add support for `.node-version`

### ISSUE THREAD

**Issue by alexanderniebuhr** [misolori/vscode-symbols#25]
not sure what a good icon is for that file, but we use `.node-version` across our projects. Currently it looks kinda sad without a custom icon.

**Comment by AnthonyLenglet** [comment]
I think the same could be used for `.nvmrc` files
for reference, in the icon pack I'm currently using (material icons), the nodejs logo is being used
<img width="87" alt="image" src="https://user-images.githubusercontent.com/36004334/184888871-5bc34373-15dd-4936-b0c5-8b092e031f73.png">

**Comment by misolori** [comment]
I'll likely use the node logo as well

**Comment by misolori** [comment]
<img width="207" alt="CleanShot 2022-08-16 at 14 59 30@2x" src="https://user-images.githubusercontent.com/35271042/184992674-990a90eb-38db-4944-89ac-5c3b0eef902c.png">
