### ISSUE TITLE
add support for storybook stories (.stories.tsx|.stories.jsx)

### ISSUE THREAD

**Issue by armandsalle** [misolori/vscode-symbols#28]
Hey 👋 your icons are so great, nice work! It's just missing icon for Storybook stories files

**Comment by misolori** [comment]
<img width="233" alt="CleanShot 2022-08-16 at 15 14 50@2x" src="https://user-images.githubusercontent.com/35271042/184994587-b75969fc-ef97-4314-8a86-985634d20199.png">
