### ISSUE TITLE
Support for GO-mod files `go.mod`, `go.sum`, `go.work`

### ISSUE THREAD

**Issue by seahindeniz** [misolori/vscode-symbols#31]
Currently
![image](https://user-images.githubusercontent.com/5789670/185050972-c87ba612-8e5a-449f-901c-cf1db2bdb0a2.png)

Material
![image](https://user-images.githubusercontent.com/5789670/185051016-b52e75fd-9e74-435e-9457-b372fd518fd5.png)

**Comment by misolori** [comment]
<img width="212" alt="CleanShot 2022-08-30 at 09 57 07@2x" src="https://user-images.githubusercontent.com/35271042/187495956-6ce0b4c2-5d83-44e9-b963-0e325b1e1856.png">
