### ISSUE TITLE
*.service.ts recognized as angular files

### ISSUE THREAD

**Issue by eliwuu** [misolori/vscode-symbols#9]
*.service is quite common on the backend, i.e. with nest.js, consider using more generic icon for *.service.ts files

**Comment by misolori** [comment]
would you expect these files to use a different icon (like `TS`) or a different color?

**Comment by varog-norman** [comment]
Agree. *.service is not using only at angular projects and i'd also like to have just *.ts icon instead

**Comment by misolori** [comment]
`*.service.ts` is now generalized

<img width="231" alt="CleanShot 2022-08-15 at 19 25 58@2x" src="https://user-images.githubusercontent.com/35271042/184785187-9ce09c6c-4a6b-4e79-bb11-627f81c04cbb.png">

**Comment by eliwuu** [comment]
<3 thank you, now it's perfect
